[archive]
build_output_dir = 'Built'
archive_location = 'C:\\Users\\labview\\Desktop\\CI\\archive'

[projects.cd]
path = 'Source\Scan Engine.lvproj'

[package]
type = 'nipkg'
payload_dir = 'source'
install_destination = 'documents\DCAF\SCANEngine'
